gitRepoUrl = "https://github.com/lockefair/roblox-utility"
gitSourceBranch = "main"

[home]
enabled = true
includeReadme = true

[docusaurus]
tagline = "A collection of object-orientated utility modules for Roblox"

[[classOrder]]
section = "Event"
classes = ["Event", "EventConnection"]

[[classOrder]]
section = "Network"
classes = ["Network", "NetworkEvent", "NetworkRequest", "NetworkValue"]