[package]
name = "lockefair/event"
description = "Signal implementation for Roblox"
version = "0.3.2"
license = "MIT"
authors = ["Joe Lunn <joe@noctua.dev>"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"