[package]
name = "lockefair/zone"
description = "Player detecting zone implementation for Roblox"
version = "0.1.4"
license = "MIT"
authors = ["Joe Lunn <joe@noctua.dev>"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Event = "lockefair/event@0.3.1"